sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
- '0.11'
- '0.12'
- '4.0'
- '5.0'
- '6.0'
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/